### ISSUE TITLE
clusten报错

### ISSUE THREAD

**Issue by whatwhyhow1** [pqh22/AdaptiveNoiseSuppression#1]
您好，请问运行的时候抛出异常RuntimeError: Could not load CLUSTEN CUDA extension. Please make sure your device has CUDA, the CUDA toolkit for PyTorch is installed, and that you've compiled CLUSTEN correctly.
我的cudn驱动和运行版本匹配的
请问这个是什么原因导致的呀

**Comment by pqh22** [comment]
clusten模块是引用自AutoFocusFormer，请参考官方实现https://github.com/apple/ml-autofocusformer

**Comment by whatwhyhow1** [comment]
实不相瞒，我是从AutoFocusFormer来的




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月14日(星期四) 晚上6:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [pqh22/AdaptiveNoiseSuppression] clusten报错 (Issue #1)














 
clusten模块是引用自AutoFocusFormer，请参考官方实现https://github.com/apple/ml-autofocusformer

**Comment by pqh22** [comment]
没有，请详细比对各模块的版本，或许可以找到问题所在。
